# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(456, 314)
        Dialog.setStyleSheet("background-color: #000")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(190, 40, 131, 61))
        self.label.setStyleSheet("color: #f7fdf9; font-size:20px; text-align: center;")
        self.label.setObjectName("label")
        self.email_line = QtWidgets.QLineEdit(Dialog)
        self.email_line.setGeometry(QtCore.QRect(100, 101, 261, 31))
        self.email_line.setStyleSheet("QLineEdit { border-radius: 4px;  color:rgb(0, 0, 0);  background-color: #f7fdf9; } QLineEdit:focus {  border-style:outset;border-width:4px; border-radius: 4px; border-color: #1db954; color: #f7fdf9; background-color: #181818; }")
        self.email_line.setObjectName("email_line")
        self.password_line = QtWidgets.QLineEdit(Dialog)
        self.password_line.setGeometry(QtCore.QRect(100, 151, 261, 31))
        self.password_line.setStyleSheet("QLineEdit { border-radius: 4px;  color:rgb(0, 0, 0);  background-color: #f7fdf9; } QLineEdit:focus {  border-style:outset;border-width:4px; border-radius: 4px; border-color: #1db954; color: #f7fdf9; background-color: #181818; }")
        self.password_line.setObjectName("password_line")
        self.accept_button = QtWidgets.QPushButton(Dialog)
        self.accept_button.setGeometry(QtCore.QRect(150, 230, 161, 41))
        self.accept_button.setStyleSheet("QPushButton { background-color: #1db954; color: #f7fdf9; border-radius: 20px; position: relative;} QPushButton:focus {position: absolute; left: -5%; width: 110%; top: -5%; height: 110%;}")
        self.accept_button.setObjectName("accept_button")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(100, 200, 261, 21))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.status_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.status_label.setStyleSheet("color: #f7fdf9;")
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.verticalLayout_2.addWidget(self.status_label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ВХОД"))
        self.accept_button.setText(_translate("Dialog", "ОК"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
