# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationPage(object):
    def setupUi(self, RegistrationPage):
        RegistrationPage.setObjectName("RegistrationPage")
        RegistrationPage.setEnabled(True)
        RegistrationPage.resize(455, 322)
        RegistrationPage.setStyleSheet("background-color: #000")
        self.label = QtWidgets.QLabel(RegistrationPage)
        self.label.setGeometry(QtCore.QRect(150, 20, 171, 61))
        self.label.setStyleSheet("color: #f7fdf9; font-size:20px; text-align: center;")
        self.label.setObjectName("label")
        self.name_line = QtWidgets.QLineEdit(RegistrationPage)
        self.name_line.setGeometry(QtCore.QRect(100, 80, 261, 31))
        self.name_line.setStyleSheet("QLineEdit { border-radius: 4px;  color:rgb(0, 0, 0);  background-color: #f7fdf9; } QLineEdit:focus {  border-style:outset;border-width:4px; border-radius: 4px; border-color: #1db954; color: #f7fdf9; background-color: #181818; }")
        self.name_line.setObjectName("name_line")
        self.email_line = QtWidgets.QLineEdit(RegistrationPage)
        self.email_line.setGeometry(QtCore.QRect(100, 121, 261, 31))
        self.email_line.setStyleSheet("QLineEdit { border-radius: 4px;  color:rgb(0, 0, 0);  background-color: #f7fdf9; } QLineEdit:focus {  border-style:outset;border-width:4px; border-radius: 4px; border-color: #1db954; color: #f7fdf9; background-color: #181818; }")
        self.email_line.setObjectName("email_line")
        self.password_line = QtWidgets.QLineEdit(RegistrationPage)
        self.password_line.setGeometry(QtCore.QRect(100, 161, 261, 31))
        self.password_line.setStyleSheet("QLineEdit { border-radius: 4px;  color:rgb(0, 0, 0);  background-color: #f7fdf9; } QLineEdit:focus {  border-style:outset;border-width:4px; border-radius: 4px; border-color: #1db954; color: #f7fdf9; background-color: #181818; }")
        self.password_line.setObjectName("password_line")
        self.password_repeat_line = QtWidgets.QLineEdit(RegistrationPage)
        self.password_repeat_line.setGeometry(QtCore.QRect(100, 201, 261, 31))
        self.password_repeat_line.setStyleSheet("QLineEdit { border-radius: 4px;  color:rgb(0, 0, 0);  background-color: #f7fdf9; } QLineEdit:focus {  border-style:outset;border-width:4px; border-radius: 4px; border-color: #1db954; color: #f7fdf9; background-color: #181818; }")
        self.password_repeat_line.setObjectName("password_repeat_line")
        self.accept_button = QtWidgets.QPushButton(RegistrationPage)
        self.accept_button.setGeometry(QtCore.QRect(140, 270, 161, 41))
        self.accept_button.setStyleSheet("QPushButton { background-color: #1db954; color: #f7fdf9; border-radius: 20px; position: relative;} QPushButton:focus {position: absolute; left: -5%; width: 110%; top: -5%; height: 110%;}")
        self.accept_button.setObjectName("accept_button")
        self.verticalLayoutWidget = QtWidgets.QWidget(RegistrationPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(99, 240, 261, 26))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.status_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.status_label.setStyleSheet("color: #f7fdf9; font-size:20px; text-align: center;")
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.verticalLayout.addWidget(self.status_label)

        self.retranslateUi(RegistrationPage)
        QtCore.QMetaObject.connectSlotsByName(RegistrationPage)

    def retranslateUi(self, RegistrationPage):
        _translate = QtCore.QCoreApplication.translate
        RegistrationPage.setWindowTitle(_translate("RegistrationPage", "Dialog"))
        self.label.setText(_translate("RegistrationPage", "Регистрация"))
        self.accept_button.setText(_translate("RegistrationPage", "ОК"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrationPage = QtWidgets.QDialog()
    ui = Ui_RegistrationPage()
    ui.setupUi(RegistrationPage)
    RegistrationPage.show()
    sys.exit(app.exec_())
